import React from 'react';
import { GlassCard } from '../components/GlassCard';

export const About: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto space-y-10 animate-fade-in">
      
      {/* Header */}
      <div className="text-center">
        <h2 className="text-4xl font-bold text-slate-900 dark:text-white mb-4">
          About MedTriage AI
        </h2>
        <p className="text-lg text-slate-600 dark:text-slate-300 leading-relaxed">
          <b>MedTriage AI</b> is a digital health triage and pharmacy support product
          designed to provide early health risk awareness using AI-powered analysis.
          It assists users in understanding potential risk levels and next steps,
          while clearly not replacing licensed medical professionals.
        </p>
      </div>

      <GlassCard className="p-8 space-y-8">

        {/* Product Objective */}
        <section>
          <h3 className="text-xl font-bold text-medical-700 dark:text-medical-400 mb-3">
            Product Objective
          </h3>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
            MedTriage AI aims to reduce unnecessary strain on healthcare facilities by
            providing an accessible, AI-driven first level of health assessment.
            The platform categorizes patient risk levels and suggests relevant medical
            specializations, ensuring critical cases are prioritized while routine
            health concerns are guided efficiently.
          </p>
        </section>

        {/* Core Modules */}
        <section>
          <h3 className="text-xl font-bold text-medical-700 dark:text-medical-400 mb-3">
            Core Product Modules
          </h3>
          <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 space-y-2">
            <li><b>Triage:</b> AI-based symptom analysis and risk categorization</li>
            <li><b>Pharmacy:</b> INR-based medicine browsing with prescription compliance</li>
            <li><b>Reports:</b> Secure access to previous health assessments</li>
            <li><b>Profile:</b> User-controlled health and personal data management</li>
          </ul>
        </section>

        {/* Technology Stack */}
        <section>
          <h3 className="text-xl font-bold text-medical-700 dark:text-medical-400 mb-3">
            Technology Stack
          </h3>
          <ul className="list-disc list-inside text-slate-600 dark:text-slate-300 space-y-2">
            <li>
              <span className="font-semibold">Frontend:</span> React with TypeScript, Vite,
              Tailwind CSS, Glassmorphism UI
            </li>
            <li>
              <span className="font-semibold">Backend:</span> Node.js with Express,
              RESTful API architecture
            </li>
            <li>
              <span className="font-semibold">Database:</span> MongoDB with Mongoose ODM
            </li>
            <li>
              <span className="font-semibold">AI Model:</span> Groq LLaMA 3 70B
            </li>
            <li>
              <span className="font-semibold">Media Storage:</span> Cloudinary (secure image uploads)
            </li>
          </ul>
        </section>

        {/* Security & Compliance */}
        <section>
          <h3 className="text-xl font-bold text-medical-700 dark:text-medical-400 mb-3">
            Security & Data Protection
          </h3>
          <p className="text-slate-600 dark:text-slate-300 leading-relaxed">
            The platform is designed with healthcare data sensitivity in mind.
            It uses secure authentication mechanisms, encrypted password storage,
            controlled API access, and environment-based configuration to protect
            user data. Users retain control over their personal information,
            including the ability to update or delete their data.
          </p>
        </section>

        {/* Disclaimer */}
        <section>
          <h3 className="text-xl font-bold text-medical-700 dark:text-medical-400 mb-3">
            Disclaimer
          </h3>
          <div className="bg-amber-50 dark:bg-amber-900/20 p-4 rounded-xl border border-amber-200 dark:border-amber-800">
            <p className="text-sm text-amber-800 dark:text-amber-200 leading-relaxed">
              MedTriage AI is developed for educational and demonstration purposes.
              All health insights and risk assessments are informational and
              probabilistic outputs generated by an AI model. This system does not
              provide medical diagnosis, treatment, or emergency care. Users must
              consult licensed medical practitioners for professional medical advice.
            </p>
          </div>
        </section>

      </GlassCard>
    </div>
  );
};
